### ISSUE TITLE
CertWare Semi-Formal Proof

### ISSUE THREAD

**Issue by jbpinch** [nasa/CertWare#11]
Every time I try to create a new Semi-Formal Proof, I get a message that says. 

"Problem Opening Wizard.  The selected wizard could not be started.
Plug-in net.certware.argument.sfp.ui was unable to load class net.certware.argument.sfp.ui.wizard.NewProofFileWizard.
An error occurred while automatically activating bundle net.certware.argument.sfp.ui (295)."  

I've tried uninstalling and reinstalling both Eclipse and CertWare, and I even tried using earlier version, Eclipse 3.7, all to no avail.

**Comment by mrbkt** [comment]
Just closing this off... the update site web page and software installation URL share the address
[http://updatesite.certware.net](http://updatesite.certware.net).  There are many new features to CertWare and SFP has been stable for quite a while.
