### ISSUE TITLE
Apache POI

### ISSUE THREAD

**Issue by abencomo** [nasa/CertWare#14]
We had the same constraint from Legal on distributing the POI bits.  Luckily, eclipse distributes them through the Orbit project so for the nasa/OpenSPIFe project, we just defined a target that points to those bundles.

http://download.eclipse.org/tools/orbit/downloads/drops/R20140114142710/repository/

HTH!

**Comment by mrbkt** [comment]
Indeed, we would like to use them in our exporters.  We missed that particular Orbit drop but will look for POI distributions there in the future.  Thanks.
