### ISSUE TITLE
Why the CertWare is imcomplete?

### ISSUE THREAD

**Issue by chaotically** [nasa/CertWare#18]
I used http://updatesite.certware.net/ as the updata URL.But the GSN Notation Support is not included.Another URL can not be use.(<https://github.com/nasa/CertWare/raw/master/net.certware.feature.updatesite>)
![20150322155641](https://cloud.githubusercontent.com/assets/11595065/6768533/1703366a-d0ac-11e4-97eb-76657a8ae6b1.png)

**Comment by mrbkt** [comment]
Updates since March 2016 include GSN along with the claim-argument-evidence and EUROCONTROL variant notations.  The raw paths no longer work owing to GitHub's policy change for large files; we have moved the update site distributions elsewhere (to the first site mentioned).
