### ISSUE TITLE
Problem with installation on Eclipse Mars.1

### ISSUE THREAD

**Issue by SafetyLok** [nasa/CertWare#19]
Hi,

While installing CertWare on Eclipse Mars.1 the installation fails with the error:

Cannot complete the install because one or more required items could not be found.
  Software being installed: CertWare GSN Notation Support 1.2.3.201504241042 (net.certware.feature.gsn.feature.group 1.2.3.201504241042)
  Missing requirement: CertWare GSN Notation Support 1.2.3.201504241042 (net.certware.feature.gsn.feature.group 1.2.3.201504241042) requires 'net.certware.argument.diagram.figures 0.0.0' but it could not be found

I ma installing from updatesite.certware.net and have pre-installed the other recommended packages.

Can anyone please help?
Thanks

**Comment by mrbkt** [comment]
The diagram figures plugin dependency unfortunately was missing from the update site build, so a fresh installation would not succeed.  A clone of the repo here could have retrieved the plugin.  Update site builds since 2/2016 repaired this problem.
